; -----------------------------------------------------------------------
; Template source file generated by piklab
    #include <p10f200.inc>

; -----------------------------------------------------------------------
; Configuration bits: adapt to your setup and needs
    __CONFIG _IntRC_OSC & _WDT_OFF & _CP_OFF & _MCLRE_OFF

; -----------------------------------------------------------------------

; GP0	hosszú gomb (on-off)
; GP1	rövid gomb (freki)
; GP2	LED


sgombbit equ	1
pgombbit equ	0
sgombmaszk equ	2
pgombmaszk equ	1

INT_VAR UDATA 0x10
w1	RES 1
w2	RES 1
w3	RES 1
w4	RES 1
sebesseg RES 1
sebessegmutato RES 1
allitas RES 1
porgeskivaro RES 1
elozogomballapot RES 1
irany RES 1
gomballapot RES 1
mute RES 1
powerstatus RES 1


; relocatable code
PROG CODE
start
    ; << ide a kódot >>
    movlw	b'00011111'	; GP2 i/o mode
    option
    movlw	d'127'		; ennyi a default sebesség
    movwf	sebessegmutato
    call	tabla
    movwf	sebesseg
    movlw	b'11111011'
    TRIS	GPIO		; GP2 output
    movlw	0x01
    movwf	allitas
    clrf	powerstatus
    clrf	irany
    clrf	mute
    clrf	porgeskivaro
    clrf	w4
    movf	GPIO,w
    movwf	gomballapot
    movwf	elozogomballapot


cikl
    movf	mute,w
    movwf	GPIO
    call	wai
    movlw	0x04
    movwf	GPIO
    call	wai
    goto	cikl
    
wai 
    movf	sebesseg,w
    movwf	w2
wai2
    decfsz	w1,f
    goto	wai2
    
    
    btfsc	porgeskivaro,3		; ha a bit "1", lepörgött
    goto	leporgott
    incf	porgeskivaro,f		; még pöröghet
    goto	nemvaltozottagomb	; ha még pörög, olyan, mintha nem változott volna a gomb	

leporgott				; számít a gomb változás
    movf	GPIO,w
    movwf	gomballapot		; elmenti a GPIO regiszter tartalmát
    andlw	0x03
    xorwf	elozogomballapot,w
    btfsc	STATUS,Z
    goto	nemvaltozottagomb
    
    clrf	porgeskivaro		; változott a gomb, pörgéskiváró indul
    btfsc	gomballapot,sgombbit	; változott a sebesség gomb?
    goto	nemkelliranyvaltas
    btfss	elozogomballapot,sgombbit
    goto	nemkelliranyvaltas
    movlw	0x01
    xorwf	irany,f			; irányt vált
nemkelliranyvaltas
    movf	gomballapot,w		; kikapcsolás kezelés !!!!!!!!!!!!!!!!!!!!!!!!
    xorwf	elozogomballapot,w
    andlw	pgombmaszk
    btfsc	STATUS,Z
    goto	nopower			; nem változott a power gomb állapota
    btfsc	gomballapot,pgombbit    ; milyen változás volt
    goto	elenged			; elenged
    btfsc	powerstatus,0		; benyom
    goto	nemmegyesbenyomjak	; 
;    bsf		mute,2			; megy és benyomják
    goto	nopower			; ennyi
nemmegyesbenyomjak
    goto	nopower
elenged
    btfss	powerstatus,0
    goto	megyeselengedik
 ;nemmegyeselengedik
    bcf		powerstatus,0
    goto	nopower

megyeselengedik
;    bsf		mute,2			; mute!
    bsf		powerstatus,0
ww4
    decfsz	w4,f			; vár a pörgésre
    goto	ww4
sll
    sleep
    movf	GPIO,w
    movwf	gomballapot
    movwf	elozogomballapot
    btfsc	elozogomballapot,pgombbit
    goto	sll			; más gombra nem ébred fel
    clrf	porgeskivaro
    clrf	powerstatus
    
    
nopower
nemvaltozottagomb



    btfsc	gomballapot,sgombbit	; nyomva van a sebesség gomb?
    goto	nemallit
    decfsz	allitas,f	; nem minden ciklusban állít rajta
    goto	nemallit
    bsf		allitas,5	; ilyen lassú az állítás
    btfsc	irany,0		; mi az irány?
    goto	eloreirany
    incf	sebessegmutato,f	; hátrairány
    goto	sebesseglepett
eloreirany
    decf	sebessegmutato,f
    
sebesseglepett
    btfsc	sebessegmutato,7	; ütköző tesztelés
    comf	sebessegmutato,f	; ütközőnél megáll a mutató
    movf	sebessegmutato,w
    call	tabla			; várakozás érték előhívása
    movwf	sebesseg		; ez lesz a sebesség
nemallit
    
    movf	gomballapot,w		; gomb állapot rögzítése
    movwf	elozogomballapot
    decfsz	w2,f
    goto	wai2
    return


tabla
    addwf	PCL,f
    retlw	d'17'
    retlw	d'17'
    retlw	d'17'
    retlw	d'18'
    retlw	d'18'
    retlw	d'18'
    retlw	d'19'
    retlw	d'19'
    retlw	d'20'
    retlw	d'20'
    retlw	d'20'
    retlw	d'21'
    retlw	d'21'
    retlw	d'22'
    retlw	d'22'
    retlw	d'23'
    retlw	d'23'
    retlw	d'24'
    retlw	d'24'
    retlw	d'25'
    retlw	d'25'
    retlw	d'26'
    retlw	d'27'
    retlw	d'27'
    retlw	d'28'
    retlw	d'28'
    retlw	d'29'
    retlw	d'30'
    retlw	d'30'
    retlw	d'31'
    retlw	d'32'
    retlw	d'32'
    retlw	d'33'
    retlw	d'34'
    retlw	d'34'
    retlw	d'35'
    retlw	d'36'
    retlw	d'37'
    retlw	d'37'
    retlw	d'38'
    retlw	d'39'
    retlw	d'40'
    retlw	d'41'
    retlw	d'42'
    retlw	d'43'
    retlw	d'44'
    retlw	d'45'
    retlw	d'45'
    retlw	d'46'
    retlw	d'47'
    retlw	d'49'
    retlw	d'50'
    retlw	d'51'
    retlw	d'52'
    retlw	d'53'
    retlw	d'54'
    retlw	d'55'
    retlw	d'56'
    retlw	d'58'
    retlw	d'59'
    retlw	d'60'
    retlw	d'62'
    retlw	d'63'
    retlw	d'64'
    retlw	d'66'
    retlw	d'67'
    retlw	d'69'
    retlw	d'70'
    retlw	d'72'
    retlw	d'73'
    retlw	d'75'
    retlw	d'76'
    retlw	d'78'
    retlw	d'80'
    retlw	d'81'
    retlw	d'83'
    retlw	d'85'
    retlw	d'87'
    retlw	d'89'
    retlw	d'91'
    retlw	d'93'
    retlw	d'95'
    retlw	d'97'
    retlw	d'99'
    retlw	d'101'
    retlw	d'103'
    retlw	d'105'
    retlw	d'108'
    retlw	d'110'
    retlw	d'112'
    retlw	d'115'
    retlw	d'117'
    retlw	d'120'
    retlw	d'123'
    retlw	d'125'
    retlw	d'128'
    retlw	d'131'
    retlw	d'134'
    retlw	d'137'
    retlw	d'140'
    retlw	d'143'
    retlw	d'146'
    retlw	d'149'
    retlw	d'152'
    retlw	d'155'
    retlw	d'159'
    retlw	d'162'
    retlw	d'166'
    retlw	d'169'
    retlw	d'173'
    retlw	d'177'
    retlw	d'181'
    retlw	d'185'
    retlw	d'189'
    retlw	d'193'
    retlw	d'197'
    retlw	d'201'
    retlw	d'206'
    retlw	d'210'
    retlw	d'215'
    retlw	d'220'
    retlw	d'224'
    retlw	d'229'
    retlw	d'234'
    retlw	d'239'
    retlw	d'245'
    retlw	d'250'
    retlw	d'255'
    
END
